-- MySQL Script generated by MySQL Workbench
-- Wed Nov 26 19:00:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema space_food
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema space_food
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `space_food` DEFAULT CHARACTER SET utf8 ;
USE `space_food` ;

-- -----------------------------------------------------
-- Table `space_food`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`Cliente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `numero_celular` VARCHAR(11) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero_casa` VARCHAR(10) NOT NULL,
  `referencia_endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space_food`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`Produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `descricao` TEXT NULL,
  `disponivel` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space_food`.`Entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`Entregador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `equipamento` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space_food`.`MeioDePagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`MeioDePagamento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space_food`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`Avaliacao` (
  `id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `descricao` TEXT NULL,
  `data` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `cliente_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`client_id`)
    REFERENCES `space_food`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space_food`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`caixa` (
  `id` INT NOT NULL,
  `nome_transacao` VARCHAR(45) NOT NULL,
  `decricao_transacao` VARCHAR(45) NULL,
  `valor_transacao` DECIMAL NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space_food`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`Pedido` (
  `id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `entrega_id` INT NULL,
  `valor_total` DECIMAL NOT NULL,
  `valor_pago` DECIMAL NULL DEFAULT 0,
  `meio_pagamento` INT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `client_id_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `delivery_id_idx` (`entrega_id` ASC) VISIBLE,
  INDEX `payment_method_id_idx` (`meio_pagamento` ASC) VISIBLE,
  CONSTRAINT `client`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `space_food`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `delivery`
    FOREIGN KEY (`entrega_id`)
    REFERENCES `space_food`.`Entregador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payment_method`
    FOREIGN KEY (`meio_pagamento`)
    REFERENCES `space_food`.`MeioDePagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space_food`.`produto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space_food`.`produto_pedido` (
  `produto_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  INDEX `produto_idx` (`produto_id` ASC) VISIBLE,
  INDEX `pedido_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `space_food`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `space_food`.`Pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
